name: old_barrel
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_phoenix: ^1.0.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.6
  blur: ^2.0.0
  solid_bottom_sheet:
    git:
      url: https://github.com/dbenitez-bcn/solid_bottom_sheet.git
  animation_wrappers: ^0.0.4
  google_mobile_ads: ^0.13.2
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  equatable: ^2.0.3
  geolocator: ^8.0.0
  geocoding: ^2.0.4
  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.4
  firebase_phone_auth_handler: ^1.0.6
  provider: ^6.0.3
  google_sign_in: ^5.4.1
  
  # buy_this_app:
  #   git:
  #     url: git@gitlab.com:verbosetech-flutter/buy-this-app-package.git
  #     ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"
  flutter_lints: ^1.0.4


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"

flutter_launcher_name:
  name: "Old Barrel"

 

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/banners/
    - assets/liquors/
    - assets/brands/
    - assets/footer menu/
    - assets/beers/
    - assets/payments/
    - assets/cards/
    - assets/payment done/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Thin.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
